# Generated by Django 3.1 on 2020-09-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appMaterial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criado', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('Modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota Fiscal')),
                ('moveimento', models.CharField(choices=[('e', 'entrada'), ('s', 'saida')], max_length=1)),
            ],
            options={
                'ordering': ('-Criado',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEstoque.estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMaterial.produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
