# Generated by Django 3.1 on 2020-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEstoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='moveimento',
            new_name='movimento',
        ),
    ]
