# Generated by Django 3.1 on 2020-09-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPrimeiraSecao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('P1', 'Primeira Seção'), ('P3', 'Terceira Seção'), ('P4', 'Quarta Seção'), ('Tes', 'Tesouraria'), ('Almox', 'Almoxarifado'), ('Almox', 'Almoxarifado'), ('Sec', 'Secretaria'), ('RMB', 'Material Bélico'), ('Transp', 'Seção de Transporte'), ('Com e TI', 'Seção de Comunicação e TI'), ('SsCOR', 'Correicional')], max_length=100)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrimeiraSecao.pessoa')),
            ],
        ),
    ]
