# Generated by Django 3.1 on 2020-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('especie', models.CharField(choices=[('Arma de fogo', 'Arma de fogo'), ('Colete', 'Colete')], max_length=15)),
                ('tipo', models.CharField(choices=[('Revr', 'Revólver'), ('Pst', 'Pistola'), ('Smtr', 'Submetralhadora'), ('Fz', 'Fuzil')], max_length=15)),
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('graduacao', models.CharField(choices=[('TC PM', 'Ten Cel PM'), ('Maj PM', 'Maj PM'), ('Cap PM', 'Cap PM'), ('1° Ten PM', '1° Ten PM'), ('2° Ten PM', '2° Ten PM'), ('ST PM', 'Sub Ten PM'), ('1° Sgt PM', '1° Sgt PM'), ('2° Sgt PM', '2° Sgt PM'), ('3° Sgt PM', '3° Sgt PM'), ('Cb PM', 'Cb PM'), ('Sd PM', 'Sd PM')], max_length=12, verbose_name='graduação')),
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_guerra', models.CharField(max_length=30, verbose_name='nome de guerra')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('patrimonio', models.IntegerField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7)),
                ('chassis', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registro em')),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.arma')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa', verbose_name='identificação')),
            ],
        ),
        migrations.CreateModel(
            name='Guarnicao',
            fields=[
                ('vtrPrefixo', models.CharField(choices=[('22000', 'operações'), ('22100', 'nazaré'), ('22115', 'CarpinaI'), ('22116', 'CarpinaII')], max_length=9, primary_key=True, serialize=False, verbose_name='prefixo')),
                ('kmInicial', models.IntegerField(verbose_name='Km inicial')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registro em')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa')),
                ('vtr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.viatura', verbose_name='patrimônio')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereço')),
                ('cidade', models.CharField(choices=[('Carpina', 'Carpina'), ('Paudalho', 'Paudalho'), ('Timbauba', 'Timbaúba'), ('Tracunhaem', 'Tracunhaém'), ('Lagoa do Carro', 'Lagoa do Carro'), ('Lagoa do Itaenga', 'Lagoa do Itaenga'), ('Buenos Aires', 'Buenos Aires'), ('Alianca', 'Aliança'), ('Camutanga', 'Camutanga'), ('Ferreiros', 'Ferreiros'), ('Macaparana', 'Macaparana'), ('Sao Vicente Ferrer', 'São Vicente Férrer'), ('Vicencia', 'Vicência'), ('Nazare da Mata', 'Nazaré da Mata')], max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PE', 'Pernambuco'), ('PB', 'Paraíba'), ('RN', 'Rio Grande do Norte')], default='PE', max_length=2)),
                ('idPessoaEndereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa', verbose_name='identificação')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel1', models.CharField(max_length=16, verbose_name='telefone')),
                ('tel2', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefone')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='e-mail')),
                ('idPessoaContato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa', verbose_name='identificação')),
            ],
        ),
    ]
