# Generated by Django 3.1 on 2020-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCreate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
