# Generated by Django 3.1 on 2020-09-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCreate', '0004_auto_20200908_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroRMB',
        ),
    ]
