# Generated by Django 3.1 on 2020-09-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0014_auto_20200914_2051'),
        ('appSsMB', '0002_auto_20200914_2051'),
        ('appCreate', '0005_delete_registrormb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arma',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='idPessoaEndereco',
        ),
        migrations.AlterField(
            model_name='guarnicao',
            name='condutor',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
