# Generated by Django 3.1 on 2020-09-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
