# Generated by Django 3.1 on 2020-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0002_auto_20200906_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id',
        ),
        migrations.AddField(
            model_name='entrada',
            name='nc',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
