# Generated by Django 3.1 on 2020-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0005_auto_20200906_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('ncSaldo', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('materialSaldo', models.CharField(max_length=100)),
                ('estoqueSaldo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
