# Generated by Django 3.1 on 2020-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0009_auto_20200908_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='estoqueMinimoSaldo',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='saldo',
            name='quantSaldo',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estoque_minimo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='nc',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='quantMaterialEntrada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='nc',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saida',
            name='quantMaterialSaida',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='ncSaldo',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
