# Generated by Django 3.1 on 2020-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmox', '0010_auto_20200908_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='nomeMaterialEntrada',
            field=models.CharField(max_length=100, verbose_name='Nome do material'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='quantMaterialEntrada',
            field=models.PositiveIntegerField(verbose_name='Quantidade do material'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='nomeMaterialSaida',
            field=models.CharField(max_length=100, verbose_name='Nome do material'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='quantMaterialSaida',
            field=models.PositiveIntegerField(verbose_name='Quantidade do material'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='ncSaldo',
            field=models.PositiveIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
