# Generated by Django 3.1 on 2020-09-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCreate', '0003_auto_20200905_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.endereco')),
                ('identificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa')),
            ],
        ),
    ]
