# Generated by Django 3.1 on 2020-09-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPessoa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info_Pessoa',
        ),
    ]
