# Generated by Django 3.1 on 2020-09-14 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCreate', '0005_delete_registrormb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('especie', models.CharField(choices=[('Arma de fogo', 'Arma de fogo'), ('Colete', 'Colete')], max_length=15)),
                ('tipo', models.CharField(choices=[('Revr', 'Revólver'), ('Pst', 'Pistola'), ('Smtr', 'Submetralhadora'), ('Fz', 'Fuzil')], max_length=15)),
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registro em')),
                ('arma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appSsMB.arma')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCreate.pessoa', verbose_name='identificação')),
            ],
        ),
    ]
