# Generated by Django 3.1 on 2020-09-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUsuarios', '0002_auto_20200902_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matriculaUsuario',
            field=models.IntegerField(null=True, verbose_name='matrícula'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nomeCompletoUsuario',
            field=models.CharField(max_length=100, null=True, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefoneUsuario',
            field=models.CharField(max_length=16, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nome de usuário'),
        ),
    ]
