# Generated by Django 3.1 on 2020-09-03 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrormb',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registro em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='idPessoaContato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appCadastros.pessoa', verbose_name='identificação'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tel1',
            field=models.CharField(max_length=16, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tel2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='idPessoaEndereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appCadastros.pessoa', verbose_name='identificação'),
        ),
        migrations.AlterField(
            model_name='guarnicao',
            name='kmInicial',
            field=models.IntegerField(verbose_name='Km inicial'),
        ),
        migrations.AlterField(
            model_name='guarnicao',
            name='vtr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCadastros.viatura', verbose_name='patrimônio'),
        ),
        migrations.AlterField(
            model_name='guarnicao',
            name='vtrPrefixo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='prefixo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_guerra',
            field=models.CharField(max_length=30, verbose_name='nome de guerra'),
        ),
        migrations.AlterField(
            model_name='registrormb',
            name='policial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCadastros.pessoa', verbose_name='identificação'),
        ),
    ]
