# Generated by Django 3.1 on 2020-09-03 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastros', '0002_auto_20200903_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarnicao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registro em'),
        ),
        migrations.AlterField(
            model_name='registrormb',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registro em'),
        ),
    ]
