# Generated by Django 3.1 on 2020-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastros', '0003_auto_20200903_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarnicao',
            name='vtrPrefixo',
            field=models.CharField(choices=[('operações', 'GT22000'), ('nazaré', 'GT22100'), ('carpinaI', 'GT22115'), ('carpinaII', 'GT22116')], max_length=9, primary_key=True, serialize=False, verbose_name='prefixo'),
        ),
    ]
