# Generated by Django 3.1 on 2020-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastros', '0004_auto_20200903_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarnicao',
            name='vtrPrefixo',
            field=models.CharField(choices=[('22000', 'operações'), ('22100', 'nazaré'), ('22115', 'CarpinaI'), ('22116', 'CarpinaII')], max_length=9, primary_key=True, serialize=False, verbose_name='prefixo'),
        ),
    ]
