# Generated by Django 3.1 on 2020-09-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('graduacao', models.CharField(choices=[('TC PM', 'Ten Cel PM'), ('Maj PM', 'Maj PM'), ('Cap PM', 'Cap PM'), ('1° Ten PM', '1° Ten PM'), ('2° Ten PM', '2° Ten PM'), ('ST PM', 'Sub Ten PM'), ('1° Sgt PM', '1° Sgt PM'), ('2° Sgt PM', '2° Sgt PM'), ('3° Sgt PM', '3° Sgt PM'), ('Cb PM', 'Cb PM'), ('Sd PM', 'Sd PM')], max_length=12, verbose_name='graduação')),
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_guerra', models.CharField(max_length=30, verbose_name='nome de guerra')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereço')),
                ('cidade', models.CharField(choices=[('Carpina', 'Carpina'), ('Paudalho', 'Paudalho'), ('Timbauba', 'Timbaúba'), ('Tracunhaem', 'Tracunhaém'), ('Lagoa do Carro', 'Lagoa do Carro'), ('Lagoa do Itaenga', 'Lagoa do Itaenga'), ('Buenos Aires', 'Buenos Aires'), ('Alianca', 'Aliança'), ('Camutanga', 'Camutanga'), ('Ferreiros', 'Ferreiros'), ('Macaparana', 'Macaparana'), ('Sao Vicente Ferrer', 'São Vicente Férrer'), ('Vicencia', 'Vicência'), ('Nazare da Mata', 'Nazaré da Mata')], max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PE', 'Pernambuco'), ('PB', 'Paraíba'), ('RN', 'Rio Grande do Norte')], default='PE', max_length=2)),
                ('idPessoaEndereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appPrimeiraSecao.pessoa', verbose_name='identificação')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel1', models.CharField(max_length=16, verbose_name='telefone')),
                ('tel2', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefone')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='e-mail')),
                ('idPessoaContato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appPrimeiraSecao.pessoa', verbose_name='identificação')),
            ],
        ),
    ]
